### ISSUE TITLE
创建数据表问题

### ISSUE THREAD

**Issue by ssxzi** [yumusb/alipay-f2fpay#1]
请问数据表如何创建，我现在创建了一个新的数据库，不会创建数据表。
下面这个怎么用
创建订单表。
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `f2f_order` (
  `id` varchar(50) NOT NULL COMMENT '订单号',
  `mark` VARCHAR(50) NOT NULL COMMENT '备注'
  `mount` varchar(20) NOT NULL COMMENT '订单金额',
  `notify_time` varchar(20) NOT NULL COMMENT '订单验证时间',
  `trade_no` varchar(30) NOT NULL COMMENT '支付宝订单号',
  `buyer_logon_id` varchar(30) NOT NULL COMMENT '付款账号',
  `status` varchar(10) NOT NULL COMMENT '订单状态'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `f2f_order`
  ADD PRIMARY KEY (`id`);
COMMIT;

**Comment by yumusb** [comment]
昨天第一次上传的时候，少写了一个逗号，最新的push已经解决。

**Comment by MoLeft** [comment]
显示订单号生成失败是什么情况，错误原因是FAILED

**Comment by yumusb** [comment]
> 显示订单号生成失败是什么情况，错误原因是FAILED

公钥/私钥问题。
