### ISSUE TITLE
关于这个当面付demo

### ISSUE THREAD

**Issue by MoLeft** [yumusb/alipay-f2fpay#3]
很久之前就再用了，刚刚看到更新了，如果能把文件的关系再理清一下就更好了，现在的话拿来二次开发还是有点小麻烦。大佬看看我二开的吧：http://pay.moleft.cn

**Comment by yumusb** [comment]
1. 文件结构  
至于文件结构，git上也有其他整理成单文件的项目。我觉得当前保留了支付宝SDK原有的目录结构，一定程度上可以帮助使用者理解。
2. 二次开发  
至于二次开发，我指的是本项目对接其他程序时候作为支付插件，之前的绝对路径写法不利于此行为。如果你愿意把你的扒皮行为称作“二次开发”，那我觉得你的二次开发还是不错的。

**Comment by InfiniteLoopCoder** [comment]
我也扒皮了，大佬把demo开源吧

**Comment by leixiaokou** [comment]
wx1361683946  一起扒皮学习吧，各位大佬  @MoLeft @yumusb @syf2005
