### ISSUE TITLE
我在notify文件中首行记录文件日志，没有接收到支付宝通知

### ISSUE THREAD

**Issue by leixiaokou** [yumusb/alipay-f2fpay#5]
支付宝回调地址已经设置。环境是宝塔，大佬知道怎么回事呢， wx 1361683946

**Comment by yumusb** [comment]
我只保证能用，不负责教配置。如果需要排查请贴出具体报错，如果需要教配置 请打赏50元以上的金额后，发送相关控制信息到我的邮箱。

**Comment by InfiniteLoopCoder** [comment]
这个是有一个小bug，直接把回调URL改成自己的网址就好

**Comment by yumusb** [comment]
> 这个是有一个小bug，直接把回调URL改成自己的网址就好

原先是使用的绑定域名，现在已经修改成了访问域名。具体可以看 [这里](https://github.com/yumusb/alipay-f2fpay/commit/4e0008c676206fb5f46e756d51364aeeb15f42f9)
